---
- name: '[Darwin] Make sure vim is installed'
  homebrew:
    name: vim
    state: present
  register: vim_install_result
  until: vim_install_result is succeeded
  become: no
  tags: vim

- name: use vi-mode in bash
  become: yes
  lineinfile:
    dest: /etc/bashrc
    line: 'set -o vi'
  tags: vim

- name: setting EDITOR bashrc
  become: yes
  lineinfile:
    dest: /etc/bashrc
    line: 'export EDITOR=vim'
  tags: vim

- name: use vi-mode in zshrc
  become: yes
  lineinfile:
    dest: /etc/zshrc
    line: 'set -o vi'

- name: setting $EDITOR
  become: yes
  lineinfile:
    dest: /etc/zshrc
    line: 'export EDITOR=vim'

- name: Set TERM environment zshrc
  become: yes
  lineinfile:
    path: /etc/zshrc
    line: 'export TERM="xterm-256color"'
  tags: vim
...
